imports:
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/parameters.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/services.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/resources.yml" }